### ISSUE TITLE
خطا در اجرای برنامه

### ISSUE THREAD

**Issue by mohsenrbb** [VahidN/PersianBingCalendar#6]
<div dir=rtl>
در هنگام اجرای برنامه در حالتی که Run as administrator نباشه خطای زیر رخ میده
</div>
<br>

```
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   at PersianBingCalendar.Core.TaskRunner.CreateOrUpdateTask()
   at PersianBingCalendar.Program.Main(String[] args)

```

**Comment by VahidN** [comment]
<div dir="rtl">

روي چه سيستمي؟
آيا نرم افزار امنيتي خاصي دسترسي برنامه را بسته؟
چون اين برنامه در حالت معمولي و بدون نياز به دسترسي ادمين، روي ويندوز 10، 8 و حتي اكس پي هم آزمايش شده و اين خطا را ندارد

پ.ن
اين مورد راه حل خاصي ندارد. به همين صورت است. اگر نمي‌توانيد اين وظيفه را اجرا كنيد، اين برنامه را فراموش كنيد
