### ISSUE TITLE
exception in task scheduler

### ISSUE THREAD

**Issue by ali-hm** [VahidN/PersianBingCalendar#8]
Is some computers the user must run the application using "Run as Administrator" or he will face this exception in error.log
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   at PersianBingCalendar.Core.TaskRunner.CreateOrUpdateTask() in D:\Ali_Hamidi\+Projects\Git\PersianBingCalendar\PersianBingCalendar\Core\TaskRunner.cs:line 25
   at PersianBingCalendar.Program.Main(String[] args) in D:\Ali_Hamidi\+Projects\Git\PersianBingCalendar\PersianBingCalendar\Program.cs:line 17

also when it is run as administrator. next scheduled runs will face this error too

**Comment by VahidN** [comment]
It can't be fixed. It's zero or one. You can run the task or you can't. That's it. I can't do anything about that.

**Comment by mohsenrbb** [comment]
@VahidN try [this](https://github.com/DavidMoore/ipfilter/commit/79a68fe198f7a616b00b581758b87dbd1330f50a)

**Comment by VahidN** [comment]
`TaskRunLevel.Highest` == Run as admin

**Comment by mohsenrbb** [comment]
when program runs as administrator, next scheduled runs will face this error too.
with this option program no longer needed to run manually.

**Comment by VahidN** [comment]
I'm not going to do that. This will require an admin privilege to run the app for the 1st time and right now I don't have this problem.
