### ISSUE TITLE
Problem in Windows 10

### ISSUE THREAD

**Issue by behiunforgiven** [VahidN/PersianBingCalendar#9]
Hi Vahid. I have windows 10 x64 and your software has  a problem with my windows. It works great on first run but it doesn't change background picture in next days.
Is there any way to find what causes this?

**Comment by VahidN** [comment]
- Are you using the [last version](https://github.com/VahidN/PersianBingCalendar/releases)? It should be V1.8.
- check out the contents of the `errors.log` file (beside the .exe file) to see are there any errors?
- check out the contents of the `last-run.log` file (beside the .exe file) to see the date of the last run.
- check out the following path in your Windows to see is there a task called `PersianBingCalendar Runner`?
```
computer managment -> task scheduler -> task scheduler library
```

**Comment by behiunforgiven** [comment]
Thanks for your answer.
Yes I'm using V1.8
and This is error log content:

`5/27/2017 10:00:02 AM
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at Microsoft.Win32.TaskScheduler.V2Interop.ITaskFolder.RegisterTaskDefinition(String Path, ITaskDefinition pDefinition, Int32 flags, Object UserId, Object password, TaskLogonType LogonType, Object sddl)
   at Microsoft.Win32.TaskScheduler.TaskFolder.RegisterTaskDefinition(String path, TaskDefinition definition, TaskCreation createType, String userId, String password, TaskLogonType logonType, String sddl)
   at PersianBingCalendar.Core.TaskRunner.CreateOrUpdateTask()
   at PersianBingCalendar.Program.Main(String[] args)`
